/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminAdminUsersRouteImport } from './routes/_admin/admin-users'
import { Route as AdminBillingRouteImport } from './routes/_admin/billing'
import { Route as AdminGeographiesRouteImport } from './routes/_admin/geographies'
import { Route as AdminTenantsIndexRouteImport } from './routes/_admin/tenants/index'
import { Route as AdminTenantsSlugRouteImport } from './routes/_admin/tenants/$slug'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeographiesRoute = AdminGeographiesRouteImport.update({
  id: '/geographies',
  path: '/geographies',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsIndexRoute = AdminTenantsIndexRouteImport.update({
  id: '/tenants/',
  path: '/tenants/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTenantsSlugRoute = AdminTenantsSlugRouteImport.update({
  id: '/tenants/$slug',
  path: '/tenants/$slug',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/login': typeof LoginRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/billing': typeof AdminBillingRoute
  '/geographies': typeof AdminGeographiesRoute
  '/tenants/$slug': typeof AdminTenantsSlugRoute
  '/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/admin-users': typeof AdminAdminUsersRoute
  '/billing': typeof AdminBillingRoute
  '/geographies': typeof AdminGeographiesRoute
  '/': typeof AdminIndexRoute
  '/tenants/$slug': typeof AdminTenantsSlugRoute
  '/tenants': typeof AdminTenantsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/_admin/admin-users': typeof AdminAdminUsersRoute
  '/_admin/billing': typeof AdminBillingRoute
  '/_admin/geographies': typeof AdminGeographiesRoute
  '/_admin/': typeof AdminIndexRoute
  '/_admin/tenants/$slug': typeof AdminTenantsSlugRoute
  '/_admin/tenants/': typeof AdminTenantsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin-users'
    | '/billing'
    | '/geographies'
    | '/tenants/$slug'
    | '/tenants/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/admin-users'
    | '/billing'
    | '/geographies'
    | '/'
    | '/tenants/$slug'
    | '/tenants'
  id:
    | '__root__'
    | '/_admin'
    | '/login'
    | '/_admin/admin-users'
    | '/_admin/billing'
    | '/_admin/geographies'
    | '/_admin/'
    | '/_admin/tenants/$slug'
    | '/_admin/tenants/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin-users': {
      id: '/_admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/billing': {
      id: '/_admin/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/geographies': {
      id: '/_admin/geographies'
      path: '/geographies'
      fullPath: '/geographies'
      preLoaderRoute: typeof AdminGeographiesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenants/': {
      id: '/_admin/tenants/'
      path: '/tenants'
      fullPath: '/tenants/'
      preLoaderRoute: typeof AdminTenantsIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/tenants/$slug': {
      id: '/_admin/tenants/$slug'
      path: '/tenants/$slug'
      fullPath: '/tenants/$slug'
      preLoaderRoute: typeof AdminTenantsSlugRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminGeographiesRoute: typeof AdminGeographiesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminTenantsSlugRoute: typeof AdminTenantsSlugRoute
  AdminTenantsIndexRoute: typeof AdminTenantsIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminGeographiesRoute: AdminGeographiesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminTenantsSlugRoute: AdminTenantsSlugRoute,
  AdminTenantsIndexRoute: AdminTenantsIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
