// The edition's app manifests, generated by vite.config.ts from editions/<EDITION>.ts (C107).
declare module 'virtual:edition' {
  import type { AppDef } from '@workspace/app-kit'
  /** The edition's name, such as 'full'. */
  export const edition: string
  /** The edition's app packages' manifests, in home-grid order. */
  export const apps: AppDef[]
}
