/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as ErrorRouteImport } from './routes/error'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RecoveryRouteImport } from './routes/recovery'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAppRouteImport } from './routes/_app/$app'
import { Route as AppAppIndexRouteImport } from './routes/_app/$app/index'
import { Route as AppAppSectionRouteImport } from './routes/_app/$app/$section'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorRoute = ErrorRouteImport.update({
  id: '/error',
  path: '/error',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoveryRoute = RecoveryRouteImport.update({
  id: '/recovery',
  path: '/recovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => AppRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppSectionRoute = AppAppSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppAppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/$app': typeof AppAppRouteWithChildren
  '/$app/$section': typeof AppAppSectionRoute
  '/$app/': typeof AppAppIndexRoute
}
export interface FileRoutesByTo {
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/': typeof AppIndexRoute
  '/$app/$section': typeof AppAppSectionRoute
  '/$app': typeof AppAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/error': typeof ErrorRoute
  '/login': typeof LoginRoute
  '/recovery': typeof RecoveryRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/_app/$app': typeof AppAppRouteWithChildren
  '/_app/': typeof AppIndexRoute
  '/_app/$app/$section': typeof AppAppSectionRoute
  '/_app/$app/': typeof AppAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/error'
    | '/login'
    | '/recovery'
    | '/settings'
    | '/verify'
    | '/$app'
    | '/$app/$section'
    | '/$app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/error'
    | '/login'
    | '/recovery'
    | '/settings'
    | '/verify'
    | '/'
    | '/$app/$section'
    | '/$app'
  id:
    | '__root__'
    | '/_app'
    | '/error'
    | '/login'
    | '/recovery'
    | '/settings'
    | '/verify'
    | '/_app/$app'
    | '/_app/'
    | '/_app/$app/$section'
    | '/_app/$app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  ErrorRoute: typeof ErrorRoute
  LoginRoute: typeof LoginRoute
  RecoveryRoute: typeof RecoveryRoute
  SettingsRoute: typeof SettingsRoute
  VerifyRoute: typeof VerifyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error': {
      id: '/error'
      path: '/error'
      fullPath: '/error'
      preLoaderRoute: typeof ErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recovery': {
      id: '/recovery'
      path: '/recovery'
      fullPath: '/recovery'
      preLoaderRoute: typeof RecoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$app': {
      id: '/_app/$app'
      path: '/$app'
      fullPath: '/$app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$app/': {
      id: '/_app/$app/'
      path: '/'
      fullPath: '/$app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/$app/$section': {
      id: '/_app/$app/$section'
      path: '/$section'
      fullPath: '/$app/$section'
      preLoaderRoute: typeof AppAppSectionRouteImport
      parentRoute: typeof AppAppRoute
    }
  }
}

interface AppAppRouteChildren {
  AppAppSectionRoute: typeof AppAppSectionRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppSectionRoute: AppAppSectionRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  ErrorRoute: ErrorRoute,
  LoginRoute: LoginRoute,
  RecoveryRoute: RecoveryRoute,
  SettingsRoute: SettingsRoute,
  VerifyRoute: VerifyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
