/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAppRouteImport } from './routes/_app/$app'
import { Route as AppNotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppAppIndexRouteImport } from './routes/_app/$app/index'
import { Route as AppAppSectionRouteImport } from './routes/_app/$app/$section'
import { Route as AppNotificationsPreferencesRouteImport } from './routes/_app/notifications_.preferences'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAppRoute = AppAppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => AppRoute,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAppRoute,
} as any)
const AppAppSectionRoute = AppAppSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppAppRoute,
} as any)
const AppNotificationsPreferencesRoute =
  AppNotificationsPreferencesRouteImport.update({
    id: '/notifications_/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => AppRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/$app': typeof AppAppRouteWithChildren
  '/notifications': typeof AppNotificationsRoute
  '/$app/$section': typeof AppAppSectionRoute
  '/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/$app/': typeof AppAppIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/notifications': typeof AppNotificationsRoute
  '/': typeof AppIndexRoute
  '/$app/$section': typeof AppAppSectionRoute
  '/notifications/preferences': typeof AppNotificationsPreferencesRoute
  '/$app': typeof AppAppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/$app': typeof AppAppRouteWithChildren
  '/_app/notifications': typeof AppNotificationsRoute
  '/_app/': typeof AppIndexRoute
  '/_app/$app/$section': typeof AppAppSectionRoute
  '/_app/notifications_/preferences': typeof AppNotificationsPreferencesRoute
  '/_app/$app/': typeof AppAppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$app'
    | '/notifications'
    | '/$app/$section'
    | '/notifications/preferences'
    | '/$app/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notifications'
    | '/'
    | '/$app/$section'
    | '/notifications/preferences'
    | '/$app'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$app'
    | '/_app/notifications'
    | '/_app/'
    | '/_app/$app/$section'
    | '/_app/notifications_/preferences'
    | '/_app/$app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$app': {
      id: '/_app/$app'
      path: '/$app'
      fullPath: '/$app'
      preLoaderRoute: typeof AppAppRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$app/': {
      id: '/_app/$app/'
      path: '/'
      fullPath: '/$app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/$app/$section': {
      id: '/_app/$app/$section'
      path: '/$section'
      fullPath: '/$app/$section'
      preLoaderRoute: typeof AppAppSectionRouteImport
      parentRoute: typeof AppAppRoute
    }
    '/_app/notifications_/preferences': {
      id: '/_app/notifications_/preferences'
      path: '/notifications/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof AppNotificationsPreferencesRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAppRouteChildren {
  AppAppSectionRoute: typeof AppAppSectionRoute
  AppAppIndexRoute: typeof AppAppIndexRoute
}

const AppAppRouteChildren: AppAppRouteChildren = {
  AppAppSectionRoute: AppAppSectionRoute,
  AppAppIndexRoute: AppAppIndexRoute,
}

const AppAppRouteWithChildren =
  AppAppRoute._addFileChildren(AppAppRouteChildren)

interface AppRouteChildren {
  AppAppRoute: typeof AppAppRouteWithChildren
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppIndexRoute: typeof AppIndexRoute
  AppNotificationsPreferencesRoute: typeof AppNotificationsPreferencesRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAppRoute: AppAppRouteWithChildren,
  AppNotificationsRoute: AppNotificationsRoute,
  AppIndexRoute: AppIndexRoute,
  AppNotificationsPreferencesRoute: AppNotificationsPreferencesRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
