package problem

import (
	"errors"
	"fmt"
	"log/slog"
	"net/http"
	"runtime"
	"runtime/debug"

	"github.com/go-chi/chi/v5/middleware"
)

// Recoverer returns middleware that turns a handler panic into a 500 problem
// details response and one ERROR log record (C38).
//
// Neither chi's middleware.Recoverer nor httplog's RecoverPanics can write a
// response body, and both log the panic outside our structured, redacted logger,
// so this is a documented gap. Register it directly after the request logger:
// the logger then records the request with status 500.
//
//   - Before the response has started: log, then answer 500 problem details.
//   - After it has started: the status and part of the body are already sent,
//     so appending an error would corrupt the response. Log, then abort the
//     connection with http.ErrAbortHandler so the client sees a failure.
//   - http.ErrAbortHandler itself is a deliberate abort: re-panic it unlogged,
//     and net/http closes the connection silently.
//
// The panic value is not logged, because it can hold arbitrary data (for example
// an error wrapping a connection string). Only Go runtime errors, whose messages
// are generated by the runtime ("index out of range [5] with length 3"), are
// logged in full; any other value is logged by type.
func Recoverer(logger *slog.Logger) func(http.Handler) http.Handler {
	return func(next http.Handler) http.Handler {
		return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
			ww := middleware.NewWrapResponseWriter(w, r.ProtoMajor)
			defer func() {
				rec := recover()
				if rec == nil {
					return
				}
				if rec == http.ErrAbortHandler { // net/http compares by identity too
					panic(rec)
				}

				started := ww.Status() != 0
				logger.ErrorContext(r.Context(), "panic recovered",
					slog.String("panic", describe(rec)),
					slog.Bool("response_started", started),
					slog.String("stack", string(debug.Stack())),
				)
				if started {
					panic(http.ErrAbortHandler)
				}
				Error(ww, r, http.StatusInternalServerError, "")
			}()
			next.ServeHTTP(ww, r)
		})
	}
}

// describe returns a loggable description of a panic value without exposing
// arbitrary data: the message for Go runtime errors, otherwise only the type.
func describe(rec any) string {
	var rtErr runtime.Error
	if err, ok := rec.(error); ok && errors.As(err, &rtErr) {
		return rtErr.Error()
	}
	return fmt.Sprintf("value of type %T", rec)
}
