// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: classification.sql

package sqlc

import (
	"context"
)

const getGlobalPartyType = `-- name: GetGlobalPartyType :one
SELECT id, country_code, party_type_class, code, name, allowed_identity_types, active_from, active_to, created_at, updated_at FROM party_types WHERE code = $1 AND country_code IS NULL
`

func (q *Queries) GetGlobalPartyType(ctx context.Context, code string) (PartyType, error) {
	row := q.db.QueryRow(ctx, getGlobalPartyType, code)
	var i PartyType
	err := row.Scan(
		&i.ID,
		&i.CountryCode,
		&i.PartyTypeClass,
		&i.Code,
		&i.Name,
		&i.AllowedIdentityTypes,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listInstitutionTypes = `-- name: ListInstitutionTypes :many
SELECT id, country_code, code, name, template_key, is_active, created_at, updated_at FROM institution_types WHERE is_active ORDER BY country_code NULLS FIRST, code
`

func (q *Queries) ListInstitutionTypes(ctx context.Context) ([]InstitutionType, error) {
	rows, err := q.db.Query(ctx, listInstitutionTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []InstitutionType{}
	for rows.Next() {
		var i InstitutionType
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.Code,
			&i.Name,
			&i.TemplateKey,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartyTypes = `-- name: ListPartyTypes :many

SELECT id, country_code, party_type_class, code, name, allowed_identity_types, active_from, active_to, created_at, updated_at FROM party_types WHERE active_to IS NULL ORDER BY party_type_class, code
`

// Classification reads (global tables). party_types drives tenant legal-form / identity-doc
// validation; institution_types selects the provisioning template.
func (q *Queries) ListPartyTypes(ctx context.Context) ([]PartyType, error) {
	rows, err := q.db.Query(ctx, listPartyTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PartyType{}
	for rows.Next() {
		var i PartyType
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.PartyTypeClass,
			&i.Code,
			&i.Name,
			&i.AllowedIdentityTypes,
			&i.ActiveFrom,
			&i.ActiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
