// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, name_i18n, phone, status, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
	Phone pgtype.Text `json:"phone"`
}

// Provisioning-created user (owner) — the only path that brings a user into existence, alongside
// the invite flow. Distinct from SyncUserOnLogin (the whoami mirror refresh): no
// last_login_at — the user hasn't signed in yet. name_i18n omitted — defaults to '{}';
// provisioning never sets it, same as it never set name_dv before.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.NameI18n,
		&i.Phone,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveUserForSession = `-- name: GetActiveUserForSession :one

SELECT id, email, name, name_i18n, phone, status, last_login_at, created_at, updated_at FROM users WHERE id = $1 AND status = 'active'
`

// Platform identity projection (control-plane; not tenant-scoped). id = Kratos subject.
// The admission check run on EVERY authenticated request: does this Kratos subject have a row, and
// is that account still active? A read, deliberately — the identical check used to be an UPDATE, so
// every request took a row lock, left a dead tuple behind, and made the API unable to serve reads
// from a replica. The write it replaced now happens only when there is something to write (see
// SyncUserOnLogin).
//
// status = 'active' is enforced here rather than left to Kratos session revocation having worked
// (FR-MEM-05 / UC-AUTH-11): a live session for a since-disabled user matches no row and is refused.
func (q *Queries) GetActiveUserForSession(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getActiveUserForSession, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.NameI18n,
		&i.Phone,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, name_i18n, phone, status, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.NameI18n,
		&i.Phone,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const syncUserOnLogin = `-- name: SyncUserOnLogin :one
UPDATE users SET
  email         = $2,
  name          = $3,
  name_i18n     = $4,
  phone         = $5,
  last_login_at = now(),
  updated_at    = now()
WHERE id = $1 AND status = 'active'
RETURNING id, email, name, name_i18n, phone, status, last_login_at, created_at, updated_at
`

type SyncUserOnLoginParams struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Name     string      `json:"name"`
	NameI18n []byte      `json:"name_i18n"`
	Phone    pgtype.Text `json:"phone"`
}

// Refresh the mirror from the Kratos identity traits and stamp the sign-in (UC-MEM-08). Run only
// when the traits have actually drifted or the stamp has gone stale — not on every request.
// UPDATE-only on purpose: there is no self-registration, so a user exists only because provisioning
// or an invite created it. An unknown subject matches no row and returns pgx.ErrNoRows, which the
// caller turns into 403 — authenticating with Kratos (password, passkey, or a future OIDC provider)
// must never be enough to become a user of this system.
//
// `status = 'active'` is enforced here too, so a disabled account is refused by our own check rather
// than only by Kratos session revocation having worked (FR-MEM-05 / UC-AUTH-11). A live session for
// a since-disabled user matches no row and is denied.
// Credentials never touch this table — Kratos owns them.
func (q *Queries) SyncUserOnLogin(ctx context.Context, arg SyncUserOnLoginParams) (User, error) {
	row := q.db.QueryRow(ctx, syncUserOnLogin,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.NameI18n,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.NameI18n,
		&i.Phone,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
