// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type App struct {
	ID           pgtype.UUID        `json:"id"`
	Code         string             `json:"code"`
	Name         string             `json:"name"`
	RequiresRole bool               `json:"requires_role"`
	ActiveFrom   pgtype.Timestamptz `json:"active_from"`
	ActiveTo     pgtype.Timestamptz `json:"active_to"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type AuditLog struct {
	ID             pgtype.UUID        `json:"id"`
	TenantID       pgtype.UUID        `json:"tenant_id"`
	ActorUserID    pgtype.UUID        `json:"actor_user_id"`
	ActingAsUserID pgtype.UUID        `json:"acting_as_user_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	Action         string             `json:"action"`
	Payload        []byte             `json:"payload"`
	RequestID      pgtype.Text        `json:"request_id"`
	Ip             *netip.Addr        `json:"ip"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

type Country struct {
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	NameI18n   []byte             `json:"name_i18n"`
	DialCode   string             `json:"dial_code"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	ActiveTo   pgtype.Timestamptz `json:"active_to"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Currency struct {
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	Symbol         string             `json:"symbol"`
	DecimalPlaces  int16              `json:"decimal_places"`
	SymbolPosition string             `json:"symbol_position"`
	ActiveFrom     pgtype.Timestamptz `json:"active_from"`
	ActiveTo       pgtype.Timestamptz `json:"active_to"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Geography struct {
	ID          pgtype.UUID        `json:"id"`
	TreeKey     int64              `json:"tree_key"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Path        string             `json:"path"`
	LevelID     pgtype.UUID        `json:"level_id"`
	CountryCode string             `json:"country_code"`
	Code        pgtype.Text        `json:"code"`
	Name        string             `json:"name"`
	NameI18n    []byte             `json:"name_i18n"`
	ActiveFrom  pgtype.Timestamptz `json:"active_from"`
	ActiveTo    pgtype.Timestamptz `json:"active_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GeographyLevel struct {
	ID          pgtype.UUID        `json:"id"`
	CountryCode pgtype.Text        `json:"country_code"`
	LevelNo     int16              `json:"level_no"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	ActiveFrom  pgtype.Timestamptz `json:"active_from"`
	ActiveTo    pgtype.Timestamptz `json:"active_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionType struct {
	ID          pgtype.UUID        `json:"id"`
	CountryCode pgtype.Text        `json:"country_code"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	TemplateKey pgtype.Text        `json:"template_key"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PartyType struct {
	ID                   pgtype.UUID        `json:"id"`
	CountryCode          pgtype.Text        `json:"country_code"`
	PartyTypeClass       string             `json:"party_type_class"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	AllowedIdentityTypes []byte             `json:"allowed_identity_types"`
	ActiveFrom           pgtype.Timestamptz `json:"active_from"`
	ActiveTo             pgtype.Timestamptz `json:"active_to"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID         pgtype.UUID        `json:"id"`
	AppID      pgtype.UUID        `json:"app_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Code       string             `json:"code"`
	Name       string             `json:"name"`
	IsDefault  bool               `json:"is_default"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	ActiveTo   pgtype.Timestamptz `json:"active_to"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type RoleCapability struct {
	ID         pgtype.UUID        `json:"id"`
	RoleID     pgtype.UUID        `json:"role_id"`
	Capability string             `json:"capability"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RoleRequest struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	TargetUserID     pgtype.UUID        `json:"target_user_id"`
	RoleID           pgtype.UUID        `json:"role_id"`
	RequestedBy      pgtype.UUID        `json:"requested_by"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	ReviewedBy       pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	ApprovedBy       pgtype.UUID        `json:"approved_by"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	ReviewDeadlineAt pgtype.Timestamptz `json:"review_deadline_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type SupportAccessGrant struct {
	ID               pgtype.UUID        `json:"id"`
	TenantID         pgtype.UUID        `json:"tenant_id"`
	TargetUserID     pgtype.UUID        `json:"target_user_id"`
	Reason           string             `json:"reason"`
	Status           string             `json:"status"`
	ProposedBy       pgtype.UUID        `json:"proposed_by"`
	ReviewedBy       pgtype.UUID        `json:"reviewed_by"`
	ReviewedAt       pgtype.Timestamptz `json:"reviewed_at"`
	ApprovedBy       pgtype.UUID        `json:"approved_by"`
	ApprovedAt       pgtype.Timestamptz `json:"approved_at"`
	TenantNotifiedAt pgtype.Timestamptz `json:"tenant_notified_at"`
	TenantApprovedBy pgtype.UUID        `json:"tenant_approved_by"`
	TenantApprovedAt pgtype.Timestamptz `json:"tenant_approved_at"`
	ReviewDeadlineAt pgtype.Timestamptz `json:"review_deadline_at"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	Code              string             `json:"code"`
	Name              string             `json:"name"`
	NameI18n          []byte             `json:"name_i18n"`
	PartyTypeID       pgtype.UUID        `json:"party_type_id"`
	InstitutionTypeID pgtype.UUID        `json:"institution_type_id"`
	IdentityType      pgtype.Text        `json:"identity_type"`
	IdentityNumber    pgtype.Text        `json:"identity_number"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	IsInternal        bool               `json:"is_internal"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	Oversight         pgtype.Text        `json:"oversight"`
	TreeKey           int64              `json:"tree_key"`
	Path              string             `json:"path"`
	Country           string             `json:"country"`
	Timezone          string             `json:"timezone"`
	Status            string             `json:"status"`
	ActiveFrom        pgtype.Timestamptz `json:"active_from"`
	ActiveTo          pgtype.Timestamptz `json:"active_to"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type TenantApp struct {
	ID          pgtype.UUID        `json:"id"`
	TenantID    pgtype.UUID        `json:"tenant_id"`
	AppID       pgtype.UUID        `json:"app_id"`
	ActivatedBy pgtype.UUID        `json:"activated_by"`
	ActiveFrom  pgtype.Timestamptz `json:"active_from"`
	ActiveTo    pgtype.Timestamptz `json:"active_to"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenantSetting struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	AppID     pgtype.UUID        `json:"app_id"`
	Key       string             `json:"key"`
	Value     []byte             `json:"value"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type TenantUser struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Status     string             `json:"status"`
	IsOwner    bool               `json:"is_owner"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	ActiveTo   pgtype.Timestamptz `json:"active_to"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	NameI18n    []byte             `json:"name_i18n"`
	Phone       pgtype.Text        `json:"phone"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserApp struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	AppID      pgtype.UUID        `json:"app_id"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	ActiveTo   pgtype.Timestamptz `json:"active_to"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type UserEfaasIdentity struct {
	UserID           pgtype.UUID        `json:"user_id"`
	EfaasSub         string             `json:"efaas_sub"`
	IDNumber         string             `json:"id_number"`
	NameEn           pgtype.Text        `json:"name_en"`
	NameDv           pgtype.Text        `json:"name_dv"`
	Dob              pgtype.Date        `json:"dob"`
	Gender           pgtype.Text        `json:"gender"`
	PermanentAddress []byte             `json:"permanent_address"`
	PresentAddress   []byte             `json:"present_address"`
	PhotoRef         pgtype.Text        `json:"photo_ref"`
	Mobile           pgtype.Text        `json:"mobile"`
	Email            pgtype.Text        `json:"email"`
	Claims           []byte             `json:"claims"`
	VerifiedAt       pgtype.Timestamptz `json:"verified_at"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	ID         pgtype.UUID        `json:"id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	UserID     pgtype.UUID        `json:"user_id"`
	RoleID     pgtype.UUID        `json:"role_id"`
	AssignedBy pgtype.UUID        `json:"assigned_by"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	ActiveTo   pgtype.Timestamptz `json:"active_to"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}
