// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type AccessGrant struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	TargetUserID pgtype.UUID        `json:"target_user_id"`
	Reason       string             `json:"reason"`
	Status       string             `json:"status"`
	ProposedBy   pgtype.UUID        `json:"proposed_by"`
	ApprovedBy   pgtype.UUID        `json:"approved_by"`
	ApprovedAt   pgtype.Timestamptz `json:"approved_at"`
	ExpiresAt    pgtype.Timestamptz `json:"expires_at"`
	RevokedAt    pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Country struct {
	Code          string             `json:"code"`
	Name          string             `json:"name"`
	NameDv        string             `json:"name_dv"`
	DialCode      string             `json:"dial_code"`
	DefaultLocale string             `json:"default_locale"`
	IsActive      bool               `json:"is_active"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Currency struct {
	Code           string             `json:"code"`
	Name           string             `json:"name"`
	NameDv         string             `json:"name_dv"`
	Symbol         string             `json:"symbol"`
	DecimalPlaces  int16              `json:"decimal_places"`
	SymbolPosition string             `json:"symbol_position"`
	IsActive       bool               `json:"is_active"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type Geography struct {
	ID          pgtype.UUID        `json:"id"`
	TreeKey     int64              `json:"tree_key"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Path        string             `json:"path"`
	LevelID     pgtype.UUID        `json:"level_id"`
	CountryCode string             `json:"country_code"`
	Code        pgtype.Text        `json:"code"`
	Name        string             `json:"name"`
	NameDv      pgtype.Text        `json:"name_dv"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GeographyLevel struct {
	ID          pgtype.UUID        `json:"id"`
	CountryCode pgtype.Text        `json:"country_code"`
	LevelNo     int16              `json:"level_no"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	NameDv      pgtype.Text        `json:"name_dv"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type InstitutionType struct {
	ID          pgtype.UUID        `json:"id"`
	CountryCode pgtype.Text        `json:"country_code"`
	ParentID    pgtype.UUID        `json:"parent_id"`
	Code        string             `json:"code"`
	Name        string             `json:"name"`
	NameDv      pgtype.Text        `json:"name_dv"`
	TemplateKey pgtype.Text        `json:"template_key"`
	IsActive    bool               `json:"is_active"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type PartyType struct {
	ID                   pgtype.UUID        `json:"id"`
	CountryCode          pgtype.Text        `json:"country_code"`
	ParentID             pgtype.UUID        `json:"parent_id"`
	PartyTypeClass       string             `json:"party_type_class"`
	Code                 string             `json:"code"`
	Name                 string             `json:"name"`
	NameDv               pgtype.Text        `json:"name_dv"`
	AllowedIdentityTypes []byte             `json:"allowed_identity_types"`
	IsActive             bool               `json:"is_active"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
}

type Role struct {
	ID        pgtype.UUID        `json:"id"`
	TenantID  pgtype.UUID        `json:"tenant_id"`
	Code      string             `json:"code"`
	Name      string             `json:"name"`
	NameDv    pgtype.Text        `json:"name_dv"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type RoleCapability struct {
	ID         pgtype.UUID        `json:"id"`
	RoleID     pgtype.UUID        `json:"role_id"`
	Capability string             `json:"capability"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type RoleChangeProposal struct {
	ID         pgtype.UUID        `json:"id"`
	Payload    []byte             `json:"payload"`
	Reason     string             `json:"reason"`
	Status     string             `json:"status"`
	ProposedBy pgtype.UUID        `json:"proposed_by"`
	ApprovedBy pgtype.UUID        `json:"approved_by"`
	ApprovedAt pgtype.Timestamptz `json:"approved_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type Tenant struct {
	ID                pgtype.UUID        `json:"id"`
	Slug              string             `json:"slug"`
	Code              string             `json:"code"`
	Name              string             `json:"name"`
	NameDv            pgtype.Text        `json:"name_dv"`
	PartyTypeID       pgtype.UUID        `json:"party_type_id"`
	InstitutionTypeID pgtype.UUID        `json:"institution_type_id"`
	IdentityType      pgtype.Text        `json:"identity_type"`
	IdentityNumber    pgtype.Text        `json:"identity_number"`
	Email             pgtype.Text        `json:"email"`
	Phone             pgtype.Text        `json:"phone"`
	IsInternal        bool               `json:"is_internal"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	Oversight         pgtype.Text        `json:"oversight"`
	TreeKey           int64              `json:"tree_key"`
	Path              string             `json:"path"`
	ConnectionKey     string             `json:"connection_key"`
	Country           string             `json:"country"`
	DefaultLocale     string             `json:"default_locale"`
	Timezone          string             `json:"timezone"`
	Status            string             `json:"status"`
	Settings          []byte             `json:"settings"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type TenantUser struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TenantID   pgtype.UUID        `json:"tenant_id"`
	Status     string             `json:"status"`
	IsOwner    bool               `json:"is_owner"`
	InvitedBy  pgtype.UUID        `json:"invited_by"`
	ActiveFrom pgtype.Timestamptz `json:"active_from"`
	ActiveTo   pgtype.Timestamptz `json:"active_to"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID          pgtype.UUID        `json:"id"`
	Email       string             `json:"email"`
	Name        string             `json:"name"`
	NameDv      pgtype.Text        `json:"name_dv"`
	Phone       pgtype.Text        `json:"phone"`
	Status      string             `json:"status"`
	LastLoginAt pgtype.Timestamptz `json:"last_login_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type UserEfaasIdentity struct {
	UserID           pgtype.UUID        `json:"user_id"`
	EfaasSub         string             `json:"efaas_sub"`
	IDNumber         string             `json:"id_number"`
	NameEn           pgtype.Text        `json:"name_en"`
	NameDv           pgtype.Text        `json:"name_dv"`
	Dob              pgtype.Date        `json:"dob"`
	Gender           pgtype.Text        `json:"gender"`
	PermanentAddress []byte             `json:"permanent_address"`
	PresentAddress   []byte             `json:"present_address"`
	PhotoRef         pgtype.Text        `json:"photo_ref"`
	Mobile           pgtype.Text        `json:"mobile"`
	Email            pgtype.Text        `json:"email"`
	Claims           []byte             `json:"claims"`
	VerifiedAt       pgtype.Timestamptz `json:"verified_at"`
	LastSyncedAt     pgtype.Timestamptz `json:"last_synced_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type UserRole struct {
	ID           pgtype.UUID        `json:"id"`
	TenantID     pgtype.UUID        `json:"tenant_id"`
	TenantUserID pgtype.UUID        `json:"tenant_user_id"`
	RoleID       pgtype.UUID        `json:"role_id"`
	AssignedBy   pgtype.UUID        `json:"assigned_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
