// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Validates a caller-supplied country code against the reference table rather than a regex: a
	// well-formed pair of letters like 'ZZ' is not a country. Requires the row to be CURRENT (active_to
	// IS NULL), so a retired country can't be chosen for something new. tenants.country is an FK to this
	// table, so without this an unknown code surfaces as a foreign-key violation from deep inside
	// provisioning — a 500 for what is really a bad field.
	ActiveCountryExists(ctx context.Context, code string) (bool, error)
	// Irreversible in this flat-CRUD pass; active_to marks the tenant as ceased (replaces deleted_at).
	// Only a live tenant can be archived: re-archiving would re-stamp active_to and move the ceased date.
	ArchiveTenant(ctx context.Context, id pgtype.UUID) (Tenant, error)
	// audit_log — append-only (DB-enforced via trg_audit_log_append_only). tenant_id is never passed
	// explicitly; it resolves from the column DEFAULT (current_setting('app.current_tenant')), so a
	// caller can only insert while running inside a tenancy.WithTenant-resolved transaction.
	// request_id ties the audited change to the request that made it — the same id in the API's logs,
	// its traces, Cerbos's decision log, and any error response the caller saw. NULL for changes with no
	// request behind them (CLI provisioning, first-run setup).
	CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLog, error)
	CreateOwnerTenantUser(ctx context.Context, arg CreateOwnerTenantUserParams) (TenantUser, error)
	CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error)
	CreateRoleCapability(ctx context.Context, arg CreateRoleCapabilityParams) (RoleCapability, error)
	// Root tenant only (parent_id/oversight NULL) — path is a single-label ltree of its own tree_key.
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// Provisioning-created user (owner) — the only path that brings a user into existence, alongside
	// the invite flow. Distinct from SyncUserOnLogin (the whoami mirror refresh): no
	// last_login_at — the user hasn't signed in yet. name_i18n omitted — defaults to '{}';
	// provisioning never sets it, same as it never set name_dv before.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UserRole, error)
	// Used by the tenant-resolution middleware: is this user a CURRENT member of this tenant?
	// "Current" is the full validity window, not just the status flag: an 'active' row whose start hasn't
	// arrived (or was never stamped) doesn't grant access yet, and one whose end has passed no longer
	// does. active_to IS NULL means "no end set" — still a member.
	GetActiveTenantMembership(ctx context.Context, arg GetActiveTenantMembershipParams) (TenantUser, error)
	GetAppByCode(ctx context.Context, code string) (App, error)
	GetCountry(ctx context.Context, code string) (Country, error)
	GetCurrency(ctx context.Context, code string) (Currency, error)
	GetGlobalPartyType(ctx context.Context, code string) (PartyType, error)
	// institution_types is "global set + country overrides" (e.g. 'council' is MV-only, 'business' is
	// global/NULL). An exact country_code = $1 match would never resolve a global row for a real
	// country argument (NULL = 'MV' is never true) — prefer a country-specific override if one exists
	// for this code, else fall back to the global row.
	GetInstitutionTypeIDByCode(ctx context.Context, arg GetInstitutionTypeIDByCodeParams) (pgtype.UUID, error)
	// At most one row can ever exist (uq_tenants_one_internal).
	GetInternalTenant(ctx context.Context) (Tenant, error)
	GetOwnerTenantUser(ctx context.Context, tenantID pgtype.UUID) (TenantUser, error)
	// Platform tenancy — control-plane (not tenant-scoped). Used by provisioning (cmd/provision-dev).
	// Global (country_code IS NULL) party types only — the app never provisions a jurisdiction-specific form here.
	GetPartyTypeIDByCode(ctx context.Context, code string) (pgtype.UUID, error)
	// tenant_id may be NULL (a global template) — a NULL query argument must match a NULL column, so
	// this uses IS NOT DISTINCT FROM rather than =, mirroring the table's own NULLS NOT DISTINCT unique
	// constraint. `tenant_id = $2` would silently never match a global role for a NULL argument (SQL's
	// three-valued logic: NULL = NULL is UNKNOWN, never TRUE).
	GetRoleByAppTenantCode(ctx context.Context, arg GetRoleByAppTenantCodeParams) (Role, error)
	GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	// FR-AUTHZ-04: platform:* capabilities only act platform-wide when held via a role on the ONE
	// internal/operator tenant, and only when the caller is genuinely a member of it.
	// Same validity window as GetActiveTenantMembership: an operator whose internal-tenant membership
	// hasn't started or has ended holds no platform-wide capabilities.
	IsInternalTenantMember(ctx context.Context, userID pgtype.UUID) (bool, error)
	// The capability slugs a user currently holds via CURRENT role assignments in one tenant — the
	// principal-building query behind authz.Authorize.
	//
	// Grants are time-bounded by design (DB-FOUNDATION: acting appointments can be scheduled ahead), so
	// "current" is the window, not just "has no end date": a grant starting next month must not confer
	// capabilities today, and one with an end date still confers them until that date arrives.
	ListActiveCapabilitiesForUserInTenant(ctx context.Context, arg ListActiveCapabilitiesForUserInTenantParams) ([]string, error)
	ListCountries(ctx context.Context) ([]Country, error)
	// Reference-data reads (global tables — no tenant scope). Starter query set to wire sqlc.
	ListCurrencies(ctx context.Context) ([]Currency, error)
	// Both the global (country_code NULL) set and any country-specific sets; resolution
	// (own set if any, else global) is applied in app logic.
	ListGeographyLevels(ctx context.Context) ([]GeographyLevel, error)
	ListInstitutionTypes(ctx context.Context) ([]InstitutionType, error)
	// Classification reads (global tables). party_types drives tenant legal-form / identity-doc
	// validation; institution_types selects the provisioning template.
	ListPartyTypes(ctx context.Context) ([]PartyType, error)
	// Operator-facing (apps/admin) tenant list — every tenant, newest first.
	ListTenants(ctx context.Context) ([]Tenant, error)
	NextTenantTreeKey(ctx context.Context) (int64, error)
	// Reversible status flip (active <-> suspended); does not touch active_to — that's archival only.
	// Guarded on the CURRENT status ($3) so the legal-transition check is atomic rather than a
	// read-then-write two concurrent operators could both win (FR-TEN-03's lifecycle order). No row
	// comes back when the tenant is not in that status — notably, an archived tenant can never be
	// flipped back to active, because archived ends the lifecycle.
	SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error)
	// Platform identity projection (control-plane; not tenant-scoped). id = Kratos subject.
	// Refresh the mirror from the Kratos identity traits and stamp the sign-in (UC-MEM-08).
	// UPDATE-only on purpose: there is no self-registration, so a user exists only because provisioning
	// or an invite created it. An unknown subject matches no row and returns pgx.ErrNoRows, which the
	// caller turns into 403 — authenticating with Kratos (password, passkey, or a future OIDC provider)
	// must never be enough to become a user of this system.
	//
	// `status = 'active'` is enforced here too, so a disabled account is refused by our own check rather
	// than only by Kratos session revocation having worked (FR-MEM-05 / UC-AUTH-11). A live session for
	// a since-disabled user matches no row and is denied.
	// Credentials never touch this table — Kratos owns them.
	SyncUserOnLogin(ctx context.Context, arg SyncUserOnLoginParams) (User, error)
}

var _ Querier = (*Queries)(nil)
