// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reference.sql

package sqlc

import (
	"context"
)

const activeCountryExists = `-- name: ActiveCountryExists :one
SELECT EXISTS (SELECT 1 FROM countries WHERE code = $1 AND active_to IS NULL)
`

// Validates a caller-supplied country code against the reference table rather than a regex: a
// well-formed pair of letters like 'ZZ' is not a country. Requires the row to be CURRENT (active_to
// IS NULL), so a retired country can't be chosen for something new. tenants.country is an FK to this
// table, so without this an unknown code surfaces as a foreign-key violation from deep inside
// provisioning — a 500 for what is really a bad field.
func (q *Queries) ActiveCountryExists(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, activeCountryExists, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const getCountry = `-- name: GetCountry :one
SELECT code, name, name_i18n, dial_code, active_from, active_to, created_at, updated_at FROM countries WHERE code = $1
`

func (q *Queries) GetCountry(ctx context.Context, code string) (Country, error) {
	row := q.db.QueryRow(ctx, getCountry, code)
	var i Country
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.NameI18n,
		&i.DialCode,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCurrency = `-- name: GetCurrency :one
SELECT code, name, symbol, decimal_places, symbol_position, active_from, active_to, created_at, updated_at FROM currencies WHERE code = $1
`

func (q *Queries) GetCurrency(ctx context.Context, code string) (Currency, error) {
	row := q.db.QueryRow(ctx, getCurrency, code)
	var i Currency
	err := row.Scan(
		&i.Code,
		&i.Name,
		&i.Symbol,
		&i.DecimalPlaces,
		&i.SymbolPosition,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCountries = `-- name: ListCountries :many
SELECT code, name, name_i18n, dial_code, active_from, active_to, created_at, updated_at FROM countries WHERE active_to IS NULL ORDER BY name
`

func (q *Queries) ListCountries(ctx context.Context) ([]Country, error) {
	rows, err := q.db.Query(ctx, listCountries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Country{}
	for rows.Next() {
		var i Country
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.NameI18n,
			&i.DialCode,
			&i.ActiveFrom,
			&i.ActiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrencies = `-- name: ListCurrencies :many

SELECT code, name, symbol, decimal_places, symbol_position, active_from, active_to, created_at, updated_at FROM currencies WHERE active_to IS NULL ORDER BY code
`

// Reference-data reads (global tables — no tenant scope). Starter query set to wire sqlc.
func (q *Queries) ListCurrencies(ctx context.Context) ([]Currency, error) {
	rows, err := q.db.Query(ctx, listCurrencies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Currency{}
	for rows.Next() {
		var i Currency
		if err := rows.Scan(
			&i.Code,
			&i.Name,
			&i.Symbol,
			&i.DecimalPlaces,
			&i.SymbolPosition,
			&i.ActiveFrom,
			&i.ActiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGeographyLevels = `-- name: ListGeographyLevels :many
SELECT id, country_code, level_no, code, name, active_from, active_to, created_at, updated_at FROM geography_levels WHERE active_to IS NULL ORDER BY country_code NULLS FIRST, level_no
`

// Both the global (country_code NULL) set and any country-specific sets; resolution
// (own set if any, else global) is applied in app logic.
func (q *Queries) ListGeographyLevels(ctx context.Context) ([]GeographyLevel, error) {
	rows, err := q.db.Query(ctx, listGeographyLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GeographyLevel{}
	for rows.Next() {
		var i GeographyLevel
		if err := rows.Scan(
			&i.ID,
			&i.CountryCode,
			&i.LevelNo,
			&i.Code,
			&i.Name,
			&i.ActiveFrom,
			&i.ActiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
