// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tenancy.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveTenant = `-- name: ArchiveTenant :one
UPDATE tenants SET status = 'archived', active_to = now(), updated_at = now() WHERE id = $1 RETURNING id, slug, code, name, name_i18n, party_type_id, institution_type_id, identity_type, identity_number, email, phone, is_internal, parent_id, oversight, tree_key, path, country, timezone, status, active_from, active_to, created_at, updated_at
`

// Irreversible in this flat-CRUD pass; active_to marks the tenant as ceased (replaces deleted_at).
func (q *Queries) ArchiveTenant(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, archiveTenant, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Code,
		&i.Name,
		&i.NameI18n,
		&i.PartyTypeID,
		&i.InstitutionTypeID,
		&i.IdentityType,
		&i.IdentityNumber,
		&i.Email,
		&i.Phone,
		&i.IsInternal,
		&i.ParentID,
		&i.Oversight,
		&i.TreeKey,
		&i.Path,
		&i.Country,
		&i.Timezone,
		&i.Status,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createOwnerTenantUser = `-- name: CreateOwnerTenantUser :one
INSERT INTO tenant_users (user_id, tenant_id, status, is_owner, active_from)
VALUES ($1, $2, 'active', true, now())
RETURNING id, user_id, tenant_id, status, is_owner, invited_by, active_from, active_to, created_at, updated_at
`

type CreateOwnerTenantUserParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
}

func (q *Queries) CreateOwnerTenantUser(ctx context.Context, arg CreateOwnerTenantUserParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, createOwnerTenantUser, arg.UserID, arg.TenantID)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Status,
		&i.IsOwner,
		&i.InvitedBy,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRole = `-- name: CreateRole :one
INSERT INTO roles (app_id, tenant_id, code, name)
VALUES ($1, $2, $3, $4)
RETURNING id, app_id, tenant_id, code, name, is_default, active_from, active_to, created_at, updated_at
`

type CreateRoleParams struct {
	AppID    pgtype.UUID `json:"app_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
	Name     string      `json:"name"`
}

func (q *Queries) CreateRole(ctx context.Context, arg CreateRoleParams) (Role, error) {
	row := q.db.QueryRow(ctx, createRole,
		arg.AppID,
		arg.TenantID,
		arg.Code,
		arg.Name,
	)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRoleCapability = `-- name: CreateRoleCapability :one
INSERT INTO role_capabilities (role_id, capability)
VALUES ($1, $2)
RETURNING id, role_id, capability, created_at
`

type CreateRoleCapabilityParams struct {
	RoleID     pgtype.UUID `json:"role_id"`
	Capability string      `json:"capability"`
}

func (q *Queries) CreateRoleCapability(ctx context.Context, arg CreateRoleCapabilityParams) (RoleCapability, error) {
	row := q.db.QueryRow(ctx, createRoleCapability, arg.RoleID, arg.Capability)
	var i RoleCapability
	err := row.Scan(
		&i.ID,
		&i.RoleID,
		&i.Capability,
		&i.CreatedAt,
	)
	return i, err
}

const createTenant = `-- name: CreateTenant :one
INSERT INTO tenants (
  slug, code, name, party_type_id, institution_type_id, tree_key, path, country, status, is_internal
) VALUES (
  $1, $2, $3, $4, $5, $6, $7::ltree, $8, $9, $10
)
RETURNING id, slug, code, name, name_i18n, party_type_id, institution_type_id, identity_type, identity_number, email, phone, is_internal, parent_id, oversight, tree_key, path, country, timezone, status, active_from, active_to, created_at, updated_at
`

type CreateTenantParams struct {
	Slug              string      `json:"slug"`
	Code              string      `json:"code"`
	Name              string      `json:"name"`
	PartyTypeID       pgtype.UUID `json:"party_type_id"`
	InstitutionTypeID pgtype.UUID `json:"institution_type_id"`
	TreeKey           int64       `json:"tree_key"`
	Column7           string      `json:"column_7"`
	Country           string      `json:"country"`
	Status            string      `json:"status"`
	IsInternal        bool        `json:"is_internal"`
}

// Root tenant only (parent_id/oversight NULL) — path is a single-label ltree of its own tree_key.
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Slug,
		arg.Code,
		arg.Name,
		arg.PartyTypeID,
		arg.InstitutionTypeID,
		arg.TreeKey,
		arg.Column7,
		arg.Country,
		arg.Status,
		arg.IsInternal,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Code,
		&i.Name,
		&i.NameI18n,
		&i.PartyTypeID,
		&i.InstitutionTypeID,
		&i.IdentityType,
		&i.IdentityNumber,
		&i.Email,
		&i.Phone,
		&i.IsInternal,
		&i.ParentID,
		&i.Oversight,
		&i.TreeKey,
		&i.Path,
		&i.Country,
		&i.Timezone,
		&i.Status,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserRole = `-- name: CreateUserRole :one
INSERT INTO user_roles (tenant_id, user_id, role_id, assigned_by)
VALUES ($1, $2, $3, $4)
RETURNING id, tenant_id, user_id, role_id, assigned_by, active_from, active_to, created_at, updated_at
`

type CreateUserRoleParams struct {
	TenantID   pgtype.UUID `json:"tenant_id"`
	UserID     pgtype.UUID `json:"user_id"`
	RoleID     pgtype.UUID `json:"role_id"`
	AssignedBy pgtype.UUID `json:"assigned_by"`
}

func (q *Queries) CreateUserRole(ctx context.Context, arg CreateUserRoleParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, createUserRole,
		arg.TenantID,
		arg.UserID,
		arg.RoleID,
		arg.AssignedBy,
	)
	var i UserRole
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.RoleID,
		&i.AssignedBy,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActiveTenantMembership = `-- name: GetActiveTenantMembership :one
SELECT tu.id, tu.user_id, tu.tenant_id, tu.status, tu.is_owner, tu.invited_by, tu.active_from, tu.active_to, tu.created_at, tu.updated_at FROM tenant_users tu
WHERE tu.tenant_id = $1 AND tu.user_id = $2 AND tu.status = 'active' AND tu.active_to IS NULL
`

type GetActiveTenantMembershipParams struct {
	TenantID pgtype.UUID `json:"tenant_id"`
	UserID   pgtype.UUID `json:"user_id"`
}

// Used by the tenant-resolution middleware: is this user a CURRENT member of this tenant?
func (q *Queries) GetActiveTenantMembership(ctx context.Context, arg GetActiveTenantMembershipParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, getActiveTenantMembership, arg.TenantID, arg.UserID)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Status,
		&i.IsOwner,
		&i.InvitedBy,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAppByCode = `-- name: GetAppByCode :one
SELECT id, code, name, requires_role, active_from, active_to, created_at, updated_at FROM apps WHERE code = $1
`

func (q *Queries) GetAppByCode(ctx context.Context, code string) (App, error) {
	row := q.db.QueryRow(ctx, getAppByCode, code)
	var i App
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.RequiresRole,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getInstitutionTypeIDByCode = `-- name: GetInstitutionTypeIDByCode :one
SELECT id FROM institution_types WHERE country_code = $1 AND code = $2
`

type GetInstitutionTypeIDByCodeParams struct {
	CountryCode pgtype.Text `json:"country_code"`
	Code        string      `json:"code"`
}

func (q *Queries) GetInstitutionTypeIDByCode(ctx context.Context, arg GetInstitutionTypeIDByCodeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getInstitutionTypeIDByCode, arg.CountryCode, arg.Code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getInternalTenant = `-- name: GetInternalTenant :one
SELECT id, slug, code, name, name_i18n, party_type_id, institution_type_id, identity_type, identity_number, email, phone, is_internal, parent_id, oversight, tree_key, path, country, timezone, status, active_from, active_to, created_at, updated_at FROM tenants WHERE is_internal
`

// At most one row can ever exist (uq_tenants_one_internal).
func (q *Queries) GetInternalTenant(ctx context.Context) (Tenant, error) {
	row := q.db.QueryRow(ctx, getInternalTenant)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Code,
		&i.Name,
		&i.NameI18n,
		&i.PartyTypeID,
		&i.InstitutionTypeID,
		&i.IdentityType,
		&i.IdentityNumber,
		&i.Email,
		&i.Phone,
		&i.IsInternal,
		&i.ParentID,
		&i.Oversight,
		&i.TreeKey,
		&i.Path,
		&i.Country,
		&i.Timezone,
		&i.Status,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOwnerTenantUser = `-- name: GetOwnerTenantUser :one
SELECT tu.id, tu.user_id, tu.tenant_id, tu.status, tu.is_owner, tu.invited_by, tu.active_from, tu.active_to, tu.created_at, tu.updated_at FROM tenant_users tu
WHERE tu.tenant_id = $1 AND tu.is_owner AND tu.active_to IS NULL
`

func (q *Queries) GetOwnerTenantUser(ctx context.Context, tenantID pgtype.UUID) (TenantUser, error) {
	row := q.db.QueryRow(ctx, getOwnerTenantUser, tenantID)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TenantID,
		&i.Status,
		&i.IsOwner,
		&i.InvitedBy,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPartyTypeIDByCode = `-- name: GetPartyTypeIDByCode :one

SELECT id FROM party_types WHERE country_code IS NULL AND code = $1
`

// Platform tenancy — control-plane (not tenant-scoped). Used by provisioning (cmd/provision-dev).
// Global (country_code IS NULL) party types only — the app never provisions a jurisdiction-specific form here.
func (q *Queries) GetPartyTypeIDByCode(ctx context.Context, code string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPartyTypeIDByCode, code)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getRoleByAppTenantCode = `-- name: GetRoleByAppTenantCode :one
SELECT id, app_id, tenant_id, code, name, is_default, active_from, active_to, created_at, updated_at FROM roles WHERE app_id = $1 AND tenant_id IS NOT DISTINCT FROM $2 AND code = $3
`

type GetRoleByAppTenantCodeParams struct {
	AppID    pgtype.UUID `json:"app_id"`
	TenantID pgtype.UUID `json:"tenant_id"`
	Code     string      `json:"code"`
}

// tenant_id may be NULL (a global template) — a NULL query argument must match a NULL column, so
// this uses IS NOT DISTINCT FROM rather than =, mirroring the table's own NULLS NOT DISTINCT unique
// constraint. `tenant_id = $2` would silently never match a global role for a NULL argument (SQL's
// three-valued logic: NULL = NULL is UNKNOWN, never TRUE).
func (q *Queries) GetRoleByAppTenantCode(ctx context.Context, arg GetRoleByAppTenantCodeParams) (Role, error) {
	row := q.db.QueryRow(ctx, getRoleByAppTenantCode, arg.AppID, arg.TenantID, arg.Code)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.AppID,
		&i.TenantID,
		&i.Code,
		&i.Name,
		&i.IsDefault,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, slug, code, name, name_i18n, party_type_id, institution_type_id, identity_type, identity_number, email, phone, is_internal, parent_id, oversight, tree_key, path, country, timezone, status, active_from, active_to, created_at, updated_at FROM tenants WHERE id = $1
`

func (q *Queries) GetTenantByID(ctx context.Context, id pgtype.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Code,
		&i.Name,
		&i.NameI18n,
		&i.PartyTypeID,
		&i.InstitutionTypeID,
		&i.IdentityType,
		&i.IdentityNumber,
		&i.Email,
		&i.Phone,
		&i.IsInternal,
		&i.ParentID,
		&i.Oversight,
		&i.TreeKey,
		&i.Path,
		&i.Country,
		&i.Timezone,
		&i.Status,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, slug, code, name, name_i18n, party_type_id, institution_type_id, identity_type, identity_number, email, phone, is_internal, parent_id, oversight, tree_key, path, country, timezone, status, active_from, active_to, created_at, updated_at FROM tenants WHERE slug = $1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Code,
		&i.Name,
		&i.NameI18n,
		&i.PartyTypeID,
		&i.InstitutionTypeID,
		&i.IdentityType,
		&i.IdentityNumber,
		&i.Email,
		&i.Phone,
		&i.IsInternal,
		&i.ParentID,
		&i.Oversight,
		&i.TreeKey,
		&i.Path,
		&i.Country,
		&i.Timezone,
		&i.Status,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenants = `-- name: ListTenants :many
SELECT id, slug, code, name, name_i18n, party_type_id, institution_type_id, identity_type, identity_number, email, phone, is_internal, parent_id, oversight, tree_key, path, country, timezone, status, active_from, active_to, created_at, updated_at FROM tenants ORDER BY created_at DESC
`

// Operator-facing (apps/admin) tenant list — every tenant, newest first.
func (q *Queries) ListTenants(ctx context.Context) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenants)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Code,
			&i.Name,
			&i.NameI18n,
			&i.PartyTypeID,
			&i.InstitutionTypeID,
			&i.IdentityType,
			&i.IdentityNumber,
			&i.Email,
			&i.Phone,
			&i.IsInternal,
			&i.ParentID,
			&i.Oversight,
			&i.TreeKey,
			&i.Path,
			&i.Country,
			&i.Timezone,
			&i.Status,
			&i.ActiveFrom,
			&i.ActiveTo,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextTenantTreeKey = `-- name: NextTenantTreeKey :one
SELECT (COALESCE(MAX(tree_key), 0) + 1)::bigint FROM tenants
`

func (q *Queries) NextTenantTreeKey(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, nextTenantTreeKey)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const setTenantStatus = `-- name: SetTenantStatus :one
UPDATE tenants SET status = $2, updated_at = now() WHERE id = $1 RETURNING id, slug, code, name, name_i18n, party_type_id, institution_type_id, identity_type, identity_number, email, phone, is_internal, parent_id, oversight, tree_key, path, country, timezone, status, active_from, active_to, created_at, updated_at
`

type SetTenantStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

// Reversible status flip (active <-> suspended); does not touch active_to — that's archival only.
func (q *Queries) SetTenantStatus(ctx context.Context, arg SetTenantStatusParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, setTenantStatus, arg.ID, arg.Status)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Code,
		&i.Name,
		&i.NameI18n,
		&i.PartyTypeID,
		&i.InstitutionTypeID,
		&i.IdentityType,
		&i.IdentityNumber,
		&i.Email,
		&i.Phone,
		&i.IsInternal,
		&i.ParentID,
		&i.Oversight,
		&i.TreeKey,
		&i.Path,
		&i.Country,
		&i.Timezone,
		&i.Status,
		&i.ActiveFrom,
		&i.ActiveTo,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
