// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, name, phone)
VALUES ($1, $2, $3, $4)
RETURNING id, email, name, name_i18n, phone, status, last_login_at, created_at, updated_at
`

type CreateUserParams struct {
	ID    pgtype.UUID `json:"id"`
	Email string      `json:"email"`
	Name  string      `json:"name"`
	Phone pgtype.Text `json:"phone"`
}

// Provisioning-created user (owner). Distinct from UpsertUser (JIT whoami mirror): no
// last_login_at — the user hasn't signed in yet. name_i18n omitted — defaults to '{}';
// provisioning never sets it, same as it never set name_dv before.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.NameI18n,
		&i.Phone,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, name_i18n, phone, status, last_login_at, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.NameI18n,
		&i.Phone,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertUser = `-- name: UpsertUser :one

INSERT INTO users (id, email, name, name_i18n, phone, last_login_at)
VALUES ($1, $2, $3, $4, $5, now())
ON CONFLICT (id) DO UPDATE SET
  email         = EXCLUDED.email,
  name          = EXCLUDED.name,
  name_i18n     = EXCLUDED.name_i18n,
  phone         = EXCLUDED.phone,
  last_login_at = now(),
  updated_at    = now()
RETURNING id, email, name, name_i18n, phone, status, last_login_at, created_at, updated_at
`

type UpsertUserParams struct {
	ID       pgtype.UUID `json:"id"`
	Email    string      `json:"email"`
	Name     string      `json:"name"`
	NameI18n []byte      `json:"name_i18n"`
	Phone    pgtype.Text `json:"phone"`
}

// Platform identity projection (control-plane; not tenant-scoped). id = Kratos subject.
// JIT-upsert the Kratos identity into platform.users on whoami (self-healing mirror).
// Credentials never touch this table — Kratos owns them.
func (q *Queries) UpsertUser(ctx context.Context, arg UpsertUserParams) (User, error) {
	row := q.db.QueryRow(ctx, upsertUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.NameI18n,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.NameI18n,
		&i.Phone,
		&i.Status,
		&i.LastLoginAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
