package postgres

import (
	"context"
	"database/sql"
	"os"
	"strings"
	"testing"
	"testing/fstest"
	"time"

	"github.com/boolmv/erp/internal/platform/config"
	"github.com/boolmv/erp/internal/platform/postgres/migrations"
	"github.com/boolmv/erp/internal/platform/postgres/migrator"
	_ "github.com/jackc/pgx/v5/stdlib"
)

func TestPostgresRuntimeAndMigrationRoles(t *testing.T) {
	bootstrapDSN := os.Getenv("POSTGRES_TEST_SETUP_DSN")
	migrationDSN := os.Getenv("POSTGRES_TEST_MIGRATE_DSN")
	appDSN := os.Getenv("POSTGRES_TEST_APP_DSN")
	if bootstrapDSN == "" || migrationDSN == "" || appDSN == "" {
		t.Skip("set POSTGRES_TEST_SETUP_DSN, POSTGRES_TEST_MIGRATE_DSN, and POSTGRES_TEST_APP_DSN to an isolated PostgreSQL database")
	}

	ctx, cancel := context.WithTimeout(t.Context(), 10*time.Second)
	defer cancel()
	const probeTable = "step3_runtime_privilege_probe"
	admin, err := sql.Open("pgx", bootstrapDSN)
	if err != nil {
		t.Fatal("open isolated database administrator connection")
	}
	if err := admin.PingContext(ctx); err != nil {
		admin.Close()
		t.Fatal("isolated database administrator connection is unavailable")
	}
	if _, err := admin.ExecContext(ctx, "DROP TABLE IF EXISTS public."+probeTable+", migrations.goose_db_version"); err != nil {
		admin.Close()
		t.Fatalf("remove stale test probe: %v", err)
	}
	t.Cleanup(func() {
		_, _ = admin.ExecContext(context.Background(), "DROP TABLE IF EXISTS public."+probeTable+", migrations.goose_db_version")
		_, _ = admin.ExecContext(context.Background(), "DROP OWNED BY erp_step3_test_app")
		_, _ = admin.ExecContext(context.Background(), "DROP OWNED BY erp_step3_test_migrate")
		_, _ = admin.ExecContext(context.Background(), "DROP ROLE IF EXISTS erp_step3_test_app, erp_step3_test_migrate")
		_ = admin.Close()
	})
	if err := provisionTestRoles(ctx, bootstrapDSN); err != nil {
		t.Fatalf("provision isolated test roles: %v", err)
	}
	files, err := migrations.Files()
	if err != nil {
		t.Fatal("load embedded migration files")
	}
	if err := migrator.Up(ctx, migrationDSN, files); err != nil {
		t.Fatalf("apply empty migration set: %v", err)
	}
	testMigrations := fstest.MapFS{
		"00001_privilege_probe.sql": {Data: []byte("-- +goose Up\nCREATE TABLE public.step3_runtime_privilege_probe (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, value text NOT NULL);\n-- +goose Down\nDROP TABLE public.step3_runtime_privilege_probe;\n")},
	}
	if err := migrator.Up(ctx, migrationDSN, testMigrations); err != nil {
		t.Fatalf("apply isolated test migration: %v", err)
	}
	var hasMigrationHistory bool
	if err := admin.QueryRowContext(ctx, "SELECT to_regclass('migrations.goose_db_version') IS NOT NULL").Scan(&hasMigrationHistory); err != nil || !hasMigrationHistory {
		t.Fatalf("migration history table is missing from its private schema: exists=%t error=%v", hasMigrationHistory, err)
	}

	pool, err := Open(ctx, config.Database{DSN: appDSN, MaxConns: 2, PingTimeout: time.Second})
	if err != nil {
		t.Fatalf("open application pool: %v", err)
	}
	defer pool.Close()
	if err := pool.Ping(ctx); err != nil {
		t.Fatalf("runtime role cannot ping PostgreSQL: %v", err)
	}
	var canUseMigrationSchema bool
	if err := pool.pool.QueryRow(ctx, "SELECT has_schema_privilege(current_user, 'migrations', 'USAGE')").Scan(&canUseMigrationSchema); err != nil || canUseMigrationSchema {
		t.Fatalf("runtime role can access migration metadata schema: canUse=%t error=%v", canUseMigrationSchema, err)
	}
	if _, err := pool.pool.Exec(ctx, "SELECT version_id FROM migrations.goose_db_version LIMIT 1"); err == nil {
		t.Fatal("runtime role unexpectedly read migration history")
	}
	var insertedID int
	if err := pool.pool.QueryRow(ctx, "INSERT INTO public."+probeTable+" (value) VALUES ('created') RETURNING id").Scan(&insertedID); err != nil {
		t.Fatalf("runtime role cannot insert into migration-owned table: %v", err)
	}
	var canSetSequence bool
	if err := pool.pool.QueryRow(ctx, "SELECT has_sequence_privilege(current_user, pg_get_serial_sequence('public."+probeTable+"', 'id'), 'UPDATE')").Scan(&canSetSequence); err != nil || canSetSequence {
		t.Fatalf("runtime role can alter an identity sequence: canSet=%t error=%v", canSetSequence, err)
	}
	var value string
	if err := pool.pool.QueryRow(ctx, "SELECT value FROM public."+probeTable+" WHERE id = $1", insertedID).Scan(&value); err != nil || value != "created" {
		t.Fatalf("runtime role cannot read migration-owned table: value=%q error=%v", value, err)
	}
	if _, err := pool.pool.Exec(ctx, "UPDATE public."+probeTable+" SET value = 'updated' WHERE id = $1", insertedID); err != nil {
		t.Fatalf("runtime role cannot update migration-owned table: %v", err)
	}
	if _, err := pool.pool.Exec(ctx, "DELETE FROM public."+probeTable+" WHERE id = $1", insertedID); err != nil {
		t.Fatalf("runtime role cannot delete migration-owned table rows: %v", err)
	}
	if _, err := pool.pool.Exec(ctx, "CREATE TABLE public.step3_runtime_must_not_create (id integer)"); err == nil {
		t.Fatal("runtime role unexpectedly has schema create permission")
	}
}

func provisionTestRoles(ctx context.Context, dsn string) error {
	db, err := sql.Open("pgx", dsn)
	if err != nil {
		return err
	}
	defer db.Close()
	if err := db.PingContext(ctx); err != nil {
		return err
	}
	for _, role := range []struct{ name, password string }{
		{"erp_step3_test_app", "step3-test-runtime"},
		{"erp_step3_test_migrate", "step3-test-migration"},
	} {
		var statement string
		err := db.QueryRowContext(ctx, `
			SELECT format(
				'CREATE ROLE %I LOGIN NOSUPERUSER NOCREATEDB NOCREATEROLE NOINHERIT PASSWORD %L',
				$1::text, $2::text
			)
			WHERE NOT EXISTS (SELECT FROM pg_roles WHERE rolname = $1::text)`, role.name, role.password).Scan(&statement)
		if err == nil {
			if _, err := db.ExecContext(ctx, statement); err != nil {
				return err
			}
		} else if err != sql.ErrNoRows {
			return err
		}
	}
	for _, statement := range []string{
		`SELECT format('GRANT CONNECT ON DATABASE %I TO erp_step3_test_app', current_database())`,
		`GRANT USAGE ON SCHEMA public TO erp_step3_test_app`,
		`SELECT format('GRANT CONNECT ON DATABASE %I TO erp_step3_test_migrate', current_database())`,
		`GRANT USAGE, CREATE ON SCHEMA public TO erp_step3_test_migrate`,
		`CREATE SCHEMA IF NOT EXISTS migrations AUTHORIZATION erp_step3_test_migrate`,
		`GRANT USAGE, CREATE ON SCHEMA migrations TO erp_step3_test_migrate`,
		`ALTER DEFAULT PRIVILEGES FOR ROLE erp_step3_test_migrate IN SCHEMA public GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO erp_step3_test_app`,
		`ALTER DEFAULT PRIVILEGES FOR ROLE erp_step3_test_migrate IN SCHEMA public GRANT USAGE ON SEQUENCES TO erp_step3_test_app`,
	} {
		if strings.HasPrefix(statement, "SELECT format(") {
			var grant string
			if err := db.QueryRowContext(ctx, statement).Scan(&grant); err != nil {
				return err
			}
			if _, err := db.ExecContext(ctx, grant); err != nil {
				return err
			}
			continue
		}
		if _, err := db.ExecContext(ctx, statement); err != nil {
			return err
		}
	}
	return nil
}
