-- Seed reference + classification data every environment needs on boot. Idempotent
-- (ON CONFLICT on natural/unique keys) so re-running `migrate up` is safe. Content confirmed
-- against DB-FOUNDATION.md seed notes. Actual geographies nodes (MV atolls/islands) are a
-- larger sourced dataset, seeded when the address feature lands.
-- +goose Up

-- currencies ----------------------------------------------------------------------------------------
INSERT INTO currencies (code, name, symbol) VALUES
  ('MVR', 'Maldivian Rufiyaa', 'Rf'),
  ('USD', 'US Dollar',         '$')
ON CONFLICT (code) DO NOTHING;

-- countries — ISO 3166-1 alpha-2. name_i18n is sparse: only populated where a real Dhivehi
-- translation exists (MV, and its closest regional neighbours IN/LK) — no fallback-to-English
-- filler, since an empty '{}' already means "no local-script name yet". dial_code = country
-- calling code. -------------------------------------------------------------------------------------
INSERT INTO countries (code, name, name_i18n, dial_code) VALUES
  ('AD','Andorra','{}','+376'),
  ('AE','United Arab Emirates','{}','+971'),
  ('AF','Afghanistan','{}','+93'),
  ('AG','Antigua and Barbuda','{}','+1'),
  ('AL','Albania','{}','+355'),
  ('AM','Armenia','{}','+374'),
  ('AO','Angola','{}','+244'),
  ('AR','Argentina','{}','+54'),
  ('AT','Austria','{}','+43'),
  ('AU','Australia','{}','+61'),
  ('AZ','Azerbaijan','{}','+994'),
  ('BA','Bosnia and Herzegovina','{}','+387'),
  ('BB','Barbados','{}','+1'),
  ('BD','Bangladesh','{}','+880'),
  ('BE','Belgium','{}','+32'),
  ('BF','Burkina Faso','{}','+226'),
  ('BG','Bulgaria','{}','+359'),
  ('BH','Bahrain','{}','+973'),
  ('BI','Burundi','{}','+257'),
  ('BJ','Benin','{}','+229'),
  ('BN','Brunei Darussalam','{}','+673'),
  ('BO','Bolivia','{}','+591'),
  ('BR','Brazil','{}','+55'),
  ('BS','Bahamas','{}','+1'),
  ('BT','Bhutan','{}','+975'),
  ('BW','Botswana','{}','+267'),
  ('BY','Belarus','{}','+375'),
  ('BZ','Belize','{}','+501'),
  ('CA','Canada','{}','+1'),
  ('CD','Congo (DRC)','{}','+243'),
  ('CF','Central African Republic','{}','+236'),
  ('CG','Congo','{}','+242'),
  ('CH','Switzerland','{}','+41'),
  ('CI','Côte d''Ivoire','{}','+225'),
  ('CL','Chile','{}','+56'),
  ('CM','Cameroon','{}','+237'),
  ('CN','China','{}','+86'),
  ('CO','Colombia','{}','+57'),
  ('CR','Costa Rica','{}','+506'),
  ('CU','Cuba','{}','+53'),
  ('CV','Cabo Verde','{}','+238'),
  ('CY','Cyprus','{}','+357'),
  ('CZ','Czechia','{}','+420'),
  ('DE','Germany','{}','+49'),
  ('DJ','Djibouti','{}','+253'),
  ('DK','Denmark','{}','+45'),
  ('DM','Dominica','{}','+1'),
  ('DO','Dominican Republic','{}','+1'),
  ('DZ','Algeria','{}','+213'),
  ('EC','Ecuador','{}','+593'),
  ('EE','Estonia','{}','+372'),
  ('EG','Egypt','{}','+20'),
  ('ER','Eritrea','{}','+291'),
  ('ES','Spain','{}','+34'),
  ('ET','Ethiopia','{}','+251'),
  ('FI','Finland','{}','+358'),
  ('FJ','Fiji','{}','+679'),
  ('FM','Micronesia','{}','+691'),
  ('FR','France','{}','+33'),
  ('GA','Gabon','{}','+241'),
  ('GB','United Kingdom','{}','+44'),
  ('GD','Grenada','{}','+1'),
  ('GE','Georgia','{}','+995'),
  ('GH','Ghana','{}','+233'),
  ('GM','Gambia','{}','+220'),
  ('GN','Guinea','{}','+224'),
  ('GQ','Equatorial Guinea','{}','+240'),
  ('GR','Greece','{}','+30'),
  ('GT','Guatemala','{}','+502'),
  ('GW','Guinea-Bissau','{}','+245'),
  ('GY','Guyana','{}','+592'),
  ('HN','Honduras','{}','+504'),
  ('HR','Croatia','{}','+385'),
  ('HT','Haiti','{}','+509'),
  ('HU','Hungary','{}','+36'),
  ('ID','Indonesia','{}','+62'),
  ('IE','Ireland','{}','+353'),
  ('IL','Israel','{}','+972'),
  ('IN','India','{"dv": "އިންޑިއާ"}','+91'),
  ('IQ','Iraq','{}','+964'),
  ('IR','Iran','{}','+98'),
  ('IS','Iceland','{}','+354'),
  ('IT','Italy','{}','+39'),
  ('JM','Jamaica','{}','+1'),
  ('JO','Jordan','{}','+962'),
  ('JP','Japan','{}','+81'),
  ('KE','Kenya','{}','+254'),
  ('KG','Kyrgyzstan','{}','+996'),
  ('KH','Cambodia','{}','+855'),
  ('KI','Kiribati','{}','+686'),
  ('KM','Comoros','{}','+269'),
  ('KN','Saint Kitts and Nevis','{}','+1'),
  ('KP','North Korea','{}','+850'),
  ('KR','South Korea','{}','+82'),
  ('KW','Kuwait','{}','+965'),
  ('KZ','Kazakhstan','{}','+7'),
  ('LA','Laos','{}','+856'),
  ('LB','Lebanon','{}','+961'),
  ('LC','Saint Lucia','{}','+1'),
  ('LI','Liechtenstein','{}','+423'),
  ('LK','Sri Lanka','{"dv": "ސްރީ ލަންކާ"}','+94'),
  ('LR','Liberia','{}','+231'),
  ('LS','Lesotho','{}','+266'),
  ('LT','Lithuania','{}','+370'),
  ('LU','Luxembourg','{}','+352'),
  ('LV','Latvia','{}','+371'),
  ('LY','Libya','{}','+218'),
  ('MA','Morocco','{}','+212'),
  ('MC','Monaco','{}','+377'),
  ('MD','Moldova','{}','+373'),
  ('ME','Montenegro','{}','+382'),
  ('MG','Madagascar','{}','+261'),
  ('MH','Marshall Islands','{}','+692'),
  ('MK','North Macedonia','{}','+389'),
  ('ML','Mali','{}','+223'),
  ('MM','Myanmar','{}','+95'),
  ('MN','Mongolia','{}','+976'),
  ('MR','Mauritania','{}','+222'),
  ('MT','Malta','{}','+356'),
  ('MU','Mauritius','{}','+230'),
  ('MV','Maldives','{"dv": "ދިވެހިރާއްޖެ"}','+960'),
  ('MW','Malawi','{}','+265'),
  ('MX','Mexico','{}','+52'),
  ('MY','Malaysia','{}','+60'),
  ('MZ','Mozambique','{}','+258'),
  ('NA','Namibia','{}','+264'),
  ('NE','Niger','{}','+227'),
  ('NG','Nigeria','{}','+234'),
  ('NI','Nicaragua','{}','+505'),
  ('NL','Netherlands','{}','+31'),
  ('NO','Norway','{}','+47'),
  ('NP','Nepal','{}','+977'),
  ('NR','Nauru','{}','+674'),
  ('NZ','New Zealand','{}','+64'),
  ('OM','Oman','{}','+968'),
  ('PA','Panama','{}','+507'),
  ('PE','Peru','{}','+51'),
  ('PG','Papua New Guinea','{}','+675'),
  ('PH','Philippines','{}','+63'),
  ('PK','Pakistan','{}','+92'),
  ('PL','Poland','{}','+48'),
  ('PS','Palestine','{}','+970'),
  ('PT','Portugal','{}','+351'),
  ('PW','Palau','{}','+680'),
  ('PY','Paraguay','{}','+595'),
  ('QA','Qatar','{}','+974'),
  ('RO','Romania','{}','+40'),
  ('RS','Serbia','{}','+381'),
  ('RU','Russia','{}','+7'),
  ('RW','Rwanda','{}','+250'),
  ('SA','Saudi Arabia','{}','+966'),
  ('SB','Solomon Islands','{}','+677'),
  ('SC','Seychelles','{}','+248'),
  ('SD','Sudan','{}','+249'),
  ('SE','Sweden','{}','+46'),
  ('SG','Singapore','{}','+65'),
  ('SI','Slovenia','{}','+386'),
  ('SK','Slovakia','{}','+421'),
  ('SL','Sierra Leone','{}','+232'),
  ('SM','San Marino','{}','+378'),
  ('SN','Senegal','{}','+221'),
  ('SO','Somalia','{}','+252'),
  ('SR','Suriname','{}','+597'),
  ('SS','South Sudan','{}','+211'),
  ('ST','Sao Tome and Principe','{}','+239'),
  ('SV','El Salvador','{}','+503'),
  ('SY','Syria','{}','+963'),
  ('SZ','Eswatini','{}','+268'),
  ('TD','Chad','{}','+235'),
  ('TG','Togo','{}','+228'),
  ('TH','Thailand','{}','+66'),
  ('TJ','Tajikistan','{}','+992'),
  ('TL','Timor-Leste','{}','+670'),
  ('TM','Turkmenistan','{}','+993'),
  ('TN','Tunisia','{}','+216'),
  ('TO','Tonga','{}','+676'),
  ('TR','Türkiye','{}','+90'),
  ('TT','Trinidad and Tobago','{}','+1'),
  ('TV','Tuvalu','{}','+688'),
  ('TW','Taiwan','{}','+886'),
  ('TZ','Tanzania','{}','+255'),
  ('UA','Ukraine','{}','+380'),
  ('UG','Uganda','{}','+256'),
  ('US','United States','{}','+1'),
  ('UY','Uruguay','{}','+598'),
  ('UZ','Uzbekistan','{}','+998'),
  ('VA','Holy See','{}','+379'),
  ('VC','Saint Vincent and the Grenadines','{}','+1'),
  ('VE','Venezuela','{}','+58'),
  ('VN','Vietnam','{}','+84'),
  ('VU','Vanuatu','{}','+678'),
  ('WS','Samoa','{}','+685'),
  ('XK','Kosovo','{}','+383'),
  ('YE','Yemen','{}','+967'),
  ('ZA','South Africa','{}','+27'),
  ('ZM','Zambia','{}','+260'),
  ('ZW','Zimbabwe','{}','+263')
ON CONFLICT (code) DO NOTHING;

-- geography_levels — global default set + Maldives-specific set. name_dv column removed
-- (form-field caption, no confirmed document-printing need). ----------------------------------------
INSERT INTO geography_levels (country_code, level_no, code, name) VALUES
  (NULL, 1, 'region',   'Region'),
  (NULL, 2, 'district', 'District'),
  (NULL, 3, 'city',     'City'),
  ('MV', 1, 'atoll',    'Atoll'),
  ('MV', 2, 'island',   'Island'),
  ('MV', 3, 'ward',     'Ward')
ON CONFLICT ON CONSTRAINT uq_geo_levels_no DO NOTHING;

-- party_types — flat (parent_id/name_dv columns removed; no rule ever walked the tree, and no
-- evidenced need to translate a taxonomy label). 'company' was a pure grouping node with no
-- identity-doc shape of its own — dropped; its two real children are now direct organisation-class
-- leaves. -------------------------------------------------------------------------------------------
INSERT INTO party_types (party_type_class, code, name, allowed_identity_types) VALUES
  ('individual',   'local',            'Local',            '["national_id"]'),
  ('individual',   'foreign',          'Foreign',          '["passport"]'),
  ('individual',   'work-permit',      'Work Permit',      '["work_permit","passport"]'),
  ('organisation', 'government',       'Government',       '[]'),
  ('organisation', 'ngo',              'NGO',              '["ngo_registration"]'),
  ('organisation', 'sole-proprietor',  'Sole Proprietor',  '["business_registration"]'),
  ('organisation', 'public-company',   'Public Company',   '["company_registration"]'),
  ('organisation', 'private-company',  'Private Company',  '["company_registration"]'),
  ('organisation', 'partnership',      'Partnership',      '["partnership_registration"]')
ON CONFLICT ON CONSTRAINT uq_party_types_code DO NOTHING;

-- institution_types — global set + MV council. Flat (parent_id/name_dv columns removed).
-- template_key selects the provisioning blueprint; NULL = generic default (Business). --------------
INSERT INTO institution_types (country_code, code, name, template_key) VALUES
  (NULL, 'business',      'Business',      NULL),
  (NULL, 'hospital',      'Hospital',      'health_facility'),
  (NULL, 'clinic',        'Clinic',        'health_facility'),
  (NULL, 'health-centre', 'Health Centre', 'health_facility'),
  (NULL, 'school',        'School',        'education'),
  (NULL, 'university',    'University',    'education'),
  (NULL, 'ministry',      'Ministry',      'government_office'),
  (NULL, 'ngo-office',    'NGO Office',    'ngo_office'),
  ('MV', 'council',       'Council',       'council')
ON CONFLICT ON CONSTRAINT uq_institution_types_code DO NOTHING;

-- +goose Down
DELETE FROM party_types WHERE country_code IS NULL AND code IN
  ('local','foreign','work-permit','government','ngo','sole-proprietor','public-company','private-company','partnership');
DELETE FROM institution_types WHERE country_code IS NULL OR (country_code = 'MV' AND code = 'council');
DELETE FROM geography_levels WHERE country_code IS NULL OR country_code = 'MV';
DELETE FROM countries;
DELETE FROM currencies;
