/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteImport } from './routes/_app'
import { Route as loginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/_app/index'
import { Route as AppRouteImport } from './routes/_app/$app'
import { Route as NotificationsRouteImport } from './routes/_app/notifications'
import { Route as AppIndexRouteImport } from './routes/_app/$app/index'
import { Route as AppSectionRouteImport } from './routes/_app/$app/$section'
import { Route as ControlCentreIndexRouteImport } from './../../../packages/app-control-centre/src/routes/index'
import { Route as ControlCentreActivityRouteImport } from './../../../packages/app-control-centre/src/routes/activity'
import { Route as ControlCentreApprovalsRouteImport } from './../../../packages/app-control-centre/src/routes/approvals'
import { Route as ControlCentreBillingRouteImport } from './../../../packages/app-control-centre/src/routes/billing'
import { Route as ControlCentreCodesRouteImport } from './../../../packages/app-control-centre/src/routes/codes'
import { Route as ControlCentreEmployeesRouteImport } from './../../../packages/app-control-centre/src/routes/employees'
import { Route as ControlCentreHolidaysRouteImport } from './../../../packages/app-control-centre/src/routes/holidays'
import { Route as ControlCentreNotificationsRouteImport } from './../../../packages/app-control-centre/src/routes/notifications'
import { Route as ControlCentreRegionsRouteImport } from './../../../packages/app-control-centre/src/routes/regions'
import { Route as ControlCentreSiteTypesRouteImport } from './../../../packages/app-control-centre/src/routes/site-types'
import { Route as ControlCentreSitesRouteImport } from './../../../packages/app-control-centre/src/routes/sites'
import { Route as ControlCentreUnitsRouteImport } from './../../../packages/app-control-centre/src/routes/units'
import { Route as Notifications_DotpreferencesRouteImport } from './routes/_app/notifications_.preferences'

const appRoute = appRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const loginRoute = loginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appRoute,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/$app',
  path: '/$app',
  getParentRoute: () => appRoute,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => appRoute,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppSectionRoute = AppSectionRouteImport.update({
  id: '/$section',
  path: '/$section',
  getParentRoute: () => AppRoute,
} as any)
const ControlCentreIndexRoute = ControlCentreIndexRouteImport.update({
  id: '/control-centre/',
  path: '/control-centre/',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreActivityRoute = ControlCentreActivityRouteImport.update({
  id: '/control-centre/activity',
  path: '/control-centre/activity',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreApprovalsRoute = ControlCentreApprovalsRouteImport.update({
  id: '/control-centre/approvals',
  path: '/control-centre/approvals',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreBillingRoute = ControlCentreBillingRouteImport.update({
  id: '/control-centre/billing',
  path: '/control-centre/billing',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreCodesRoute = ControlCentreCodesRouteImport.update({
  id: '/control-centre/codes',
  path: '/control-centre/codes',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreEmployeesRoute = ControlCentreEmployeesRouteImport.update({
  id: '/control-centre/employees',
  path: '/control-centre/employees',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreHolidaysRoute = ControlCentreHolidaysRouteImport.update({
  id: '/control-centre/holidays',
  path: '/control-centre/holidays',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreNotificationsRoute =
  ControlCentreNotificationsRouteImport.update({
    id: '/control-centre/notifications',
    path: '/control-centre/notifications',
    getParentRoute: () => appRoute,
  } as any)
const ControlCentreRegionsRoute = ControlCentreRegionsRouteImport.update({
  id: '/control-centre/regions',
  path: '/control-centre/regions',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreSiteTypesRoute = ControlCentreSiteTypesRouteImport.update({
  id: '/control-centre/site-types',
  path: '/control-centre/site-types',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreSitesRoute = ControlCentreSitesRouteImport.update({
  id: '/control-centre/sites',
  path: '/control-centre/sites',
  getParentRoute: () => appRoute,
} as any)
const ControlCentreUnitsRoute = ControlCentreUnitsRouteImport.update({
  id: '/control-centre/units',
  path: '/control-centre/units',
  getParentRoute: () => appRoute,
} as any)
const Notifications_DotpreferencesRoute =
  Notifications_DotpreferencesRouteImport.update({
    id: '/notifications_/preferences',
    path: '/notifications/preferences',
    getParentRoute: () => appRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof loginRoute
  '/$app': typeof AppRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/$app/$section': typeof AppSectionRoute
  '/control-centre/activity': typeof ControlCentreActivityRoute
  '/control-centre/approvals': typeof ControlCentreApprovalsRoute
  '/control-centre/billing': typeof ControlCentreBillingRoute
  '/control-centre/codes': typeof ControlCentreCodesRoute
  '/control-centre/employees': typeof ControlCentreEmployeesRoute
  '/control-centre/holidays': typeof ControlCentreHolidaysRoute
  '/control-centre/notifications': typeof ControlCentreNotificationsRoute
  '/control-centre/regions': typeof ControlCentreRegionsRoute
  '/control-centre/site-types': typeof ControlCentreSiteTypesRoute
  '/control-centre/sites': typeof ControlCentreSitesRoute
  '/control-centre/units': typeof ControlCentreUnitsRoute
  '/notifications/preferences': typeof Notifications_DotpreferencesRoute
  '/$app/': typeof AppIndexRoute
  '/control-centre/': typeof ControlCentreIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof loginRoute
  '/notifications': typeof NotificationsRoute
  '/': typeof IndexRoute
  '/$app/$section': typeof AppSectionRoute
  '/control-centre/activity': typeof ControlCentreActivityRoute
  '/control-centre/approvals': typeof ControlCentreApprovalsRoute
  '/control-centre/billing': typeof ControlCentreBillingRoute
  '/control-centre/codes': typeof ControlCentreCodesRoute
  '/control-centre/employees': typeof ControlCentreEmployeesRoute
  '/control-centre/holidays': typeof ControlCentreHolidaysRoute
  '/control-centre/notifications': typeof ControlCentreNotificationsRoute
  '/control-centre/regions': typeof ControlCentreRegionsRoute
  '/control-centre/site-types': typeof ControlCentreSiteTypesRoute
  '/control-centre/sites': typeof ControlCentreSitesRoute
  '/control-centre/units': typeof ControlCentreUnitsRoute
  '/notifications/preferences': typeof Notifications_DotpreferencesRoute
  '/$app': typeof AppIndexRoute
  '/control-centre': typeof ControlCentreIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof appRouteWithChildren
  '/login': typeof loginRoute
  '/_app/$app': typeof AppRouteWithChildren
  '/_app/notifications': typeof NotificationsRoute
  '/_app/': typeof IndexRoute
  '/_app/$app/$section': typeof AppSectionRoute
  '/_app/control-centre/activity': typeof ControlCentreActivityRoute
  '/_app/control-centre/approvals': typeof ControlCentreApprovalsRoute
  '/_app/control-centre/billing': typeof ControlCentreBillingRoute
  '/_app/control-centre/codes': typeof ControlCentreCodesRoute
  '/_app/control-centre/employees': typeof ControlCentreEmployeesRoute
  '/_app/control-centre/holidays': typeof ControlCentreHolidaysRoute
  '/_app/control-centre/notifications': typeof ControlCentreNotificationsRoute
  '/_app/control-centre/regions': typeof ControlCentreRegionsRoute
  '/_app/control-centre/site-types': typeof ControlCentreSiteTypesRoute
  '/_app/control-centre/sites': typeof ControlCentreSitesRoute
  '/_app/control-centre/units': typeof ControlCentreUnitsRoute
  '/_app/notifications_/preferences': typeof Notifications_DotpreferencesRoute
  '/_app/$app/': typeof AppIndexRoute
  '/_app/control-centre/': typeof ControlCentreIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/$app'
    | '/notifications'
    | '/$app/$section'
    | '/control-centre/activity'
    | '/control-centre/approvals'
    | '/control-centre/billing'
    | '/control-centre/codes'
    | '/control-centre/employees'
    | '/control-centre/holidays'
    | '/control-centre/notifications'
    | '/control-centre/regions'
    | '/control-centre/site-types'
    | '/control-centre/sites'
    | '/control-centre/units'
    | '/notifications/preferences'
    | '/$app/'
    | '/control-centre/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/notifications'
    | '/'
    | '/$app/$section'
    | '/control-centre/activity'
    | '/control-centre/approvals'
    | '/control-centre/billing'
    | '/control-centre/codes'
    | '/control-centre/employees'
    | '/control-centre/holidays'
    | '/control-centre/notifications'
    | '/control-centre/regions'
    | '/control-centre/site-types'
    | '/control-centre/sites'
    | '/control-centre/units'
    | '/notifications/preferences'
    | '/$app'
    | '/control-centre'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/$app'
    | '/_app/notifications'
    | '/_app/'
    | '/_app/$app/$section'
    | '/_app/control-centre/activity'
    | '/_app/control-centre/approvals'
    | '/_app/control-centre/billing'
    | '/_app/control-centre/codes'
    | '/_app/control-centre/employees'
    | '/_app/control-centre/holidays'
    | '/_app/control-centre/notifications'
    | '/_app/control-centre/regions'
    | '/_app/control-centre/site-types'
    | '/_app/control-centre/sites'
    | '/_app/control-centre/units'
    | '/_app/notifications_/preferences'
    | '/_app/$app/'
    | '/_app/control-centre/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  appRoute: typeof appRouteWithChildren
  loginRoute: typeof loginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof appRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof loginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/$app': {
      id: '/_app/$app'
      path: '/$app'
      fullPath: '/$app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/notifications': {
      id: '/_app/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/$app/': {
      id: '/_app/$app/'
      path: '/'
      fullPath: '/$app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/$app/$section': {
      id: '/_app/$app/$section'
      path: '/$section'
      fullPath: '/$app/$section'
      preLoaderRoute: typeof AppSectionRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/control-centre/': {
      id: '/_app/control-centre/'
      path: '/control-centre'
      fullPath: '/control-centre/'
      preLoaderRoute: typeof ControlCentreIndexRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/activity': {
      id: '/_app/control-centre/activity'
      path: '/control-centre/activity'
      fullPath: '/control-centre/activity'
      preLoaderRoute: typeof ControlCentreActivityRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/approvals': {
      id: '/_app/control-centre/approvals'
      path: '/control-centre/approvals'
      fullPath: '/control-centre/approvals'
      preLoaderRoute: typeof ControlCentreApprovalsRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/billing': {
      id: '/_app/control-centre/billing'
      path: '/control-centre/billing'
      fullPath: '/control-centre/billing'
      preLoaderRoute: typeof ControlCentreBillingRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/codes': {
      id: '/_app/control-centre/codes'
      path: '/control-centre/codes'
      fullPath: '/control-centre/codes'
      preLoaderRoute: typeof ControlCentreCodesRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/employees': {
      id: '/_app/control-centre/employees'
      path: '/control-centre/employees'
      fullPath: '/control-centre/employees'
      preLoaderRoute: typeof ControlCentreEmployeesRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/holidays': {
      id: '/_app/control-centre/holidays'
      path: '/control-centre/holidays'
      fullPath: '/control-centre/holidays'
      preLoaderRoute: typeof ControlCentreHolidaysRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/notifications': {
      id: '/_app/control-centre/notifications'
      path: '/control-centre/notifications'
      fullPath: '/control-centre/notifications'
      preLoaderRoute: typeof ControlCentreNotificationsRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/regions': {
      id: '/_app/control-centre/regions'
      path: '/control-centre/regions'
      fullPath: '/control-centre/regions'
      preLoaderRoute: typeof ControlCentreRegionsRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/site-types': {
      id: '/_app/control-centre/site-types'
      path: '/control-centre/site-types'
      fullPath: '/control-centre/site-types'
      preLoaderRoute: typeof ControlCentreSiteTypesRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/sites': {
      id: '/_app/control-centre/sites'
      path: '/control-centre/sites'
      fullPath: '/control-centre/sites'
      preLoaderRoute: typeof ControlCentreSitesRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/control-centre/units': {
      id: '/_app/control-centre/units'
      path: '/control-centre/units'
      fullPath: '/control-centre/units'
      preLoaderRoute: typeof ControlCentreUnitsRouteImport
      parentRoute: typeof appRoute
    }
    '/_app/notifications_/preferences': {
      id: '/_app/notifications_/preferences'
      path: '/notifications/preferences'
      fullPath: '/notifications/preferences'
      preLoaderRoute: typeof Notifications_DotpreferencesRouteImport
      parentRoute: typeof appRoute
    }
  }
}

interface AppRouteChildren {
  AppSectionRoute: typeof AppSectionRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppSectionRoute: AppSectionRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface appRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  IndexRoute: typeof IndexRoute
  ControlCentreActivityRoute: typeof ControlCentreActivityRoute
  ControlCentreApprovalsRoute: typeof ControlCentreApprovalsRoute
  ControlCentreBillingRoute: typeof ControlCentreBillingRoute
  ControlCentreCodesRoute: typeof ControlCentreCodesRoute
  ControlCentreEmployeesRoute: typeof ControlCentreEmployeesRoute
  ControlCentreHolidaysRoute: typeof ControlCentreHolidaysRoute
  ControlCentreNotificationsRoute: typeof ControlCentreNotificationsRoute
  ControlCentreRegionsRoute: typeof ControlCentreRegionsRoute
  ControlCentreSiteTypesRoute: typeof ControlCentreSiteTypesRoute
  ControlCentreSitesRoute: typeof ControlCentreSitesRoute
  ControlCentreUnitsRoute: typeof ControlCentreUnitsRoute
  Notifications_DotpreferencesRoute: typeof Notifications_DotpreferencesRoute
  ControlCentreIndexRoute: typeof ControlCentreIndexRoute
}

const appRouteChildren: appRouteChildren = {
  AppRoute: AppRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  IndexRoute: IndexRoute,
  ControlCentreActivityRoute: ControlCentreActivityRoute,
  ControlCentreApprovalsRoute: ControlCentreApprovalsRoute,
  ControlCentreBillingRoute: ControlCentreBillingRoute,
  ControlCentreCodesRoute: ControlCentreCodesRoute,
  ControlCentreEmployeesRoute: ControlCentreEmployeesRoute,
  ControlCentreHolidaysRoute: ControlCentreHolidaysRoute,
  ControlCentreNotificationsRoute: ControlCentreNotificationsRoute,
  ControlCentreRegionsRoute: ControlCentreRegionsRoute,
  ControlCentreSiteTypesRoute: ControlCentreSiteTypesRoute,
  ControlCentreSitesRoute: ControlCentreSitesRoute,
  ControlCentreUnitsRoute: ControlCentreUnitsRoute,
  Notifications_DotpreferencesRoute: Notifications_DotpreferencesRoute,
  ControlCentreIndexRoute: ControlCentreIndexRoute,
}

const appRouteWithChildren = appRoute._addFileChildren(appRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  appRoute: appRouteWithChildren,
  loginRoute: loginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
